# Generated by Django 5.0.2 on 2024-03-02 06:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_rename_own_bathroom_filter_personal_bathroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='beds',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='location',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='personal_bathroom',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
        migrations.AddField(
            model_name='listing',
            name='parameters',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter.filter'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='length_of_stay',
            field=models.IntegerField(choices=[(4, '4 months'), (8, '8 months'), (12, '12 months')], default=4, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='move_in_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
