# Generated by Django 5.0.2 on 2024-03-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_listing_parameters_alter_listing_parameters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing_parameters',
            name='gender',
            field=models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'either')], default=2),
        ),
        migrations.AddField(
            model_name='listing_parameters',
            name='personal_bathroom',
            field=models.BooleanField(default=False),
        ),
    ]
