# Generated by Django 5.0.2 on 2024-03-28 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_listing_parameters_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing_parameters',
            name='neighbourhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter.neighbourhood'),
        ),
    ]
