# Generated by Django 5.0.2 on 2024-03-29 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_listing_parameters_neighbourhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_filter',
            name='length_of_stay',
            field=models.IntegerField(choices=[(4, '4 months'), (8, '8 months'), (12, '12 months')], default=4, null=True),
        ),
        migrations.AddField(
            model_name='user_filter',
            name='move_in_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
