# Generated by Django 5.0.2 on 2024-04-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0010_user_filter_length_of_stay_user_filter_move_in_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_filter',
            old_name='min_bathrooms',
            new_name='max_baths',
        ),
        migrations.RenameField(
            model_name='user_filter',
            old_name='price_range',
            new_name='price_limit',
        ),
        migrations.AddField(
            model_name='user_filter',
            name='max_beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_filter',
            name='min_baths',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_filter',
            name='min_beds',
            field=models.IntegerField(),
        ),
    ]
