# Generated by Django 5.0.2 on 2024-04-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0011_rename_min_bathrooms_user_filter_max_baths_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_filter',
            name='max_baths',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_filter',
            name='max_beds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_filter',
            name='min_baths',
            field=models.IntegerField(),
        ),
    ]
