# Generated by Django 5.0.2 on 2024-04-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0012_alter_user_filter_max_baths_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_filter',
            name='max_baths',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_filter',
            name='max_beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_filter',
            name='min_baths',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_filter',
            name='min_beds',
            field=models.IntegerField(default=0),
        ),
    ]
