# Generated by Django 5.0.2 on 2024-04-04 04:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0013_alter_user_filter_max_baths_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='listing_parameters',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
