# Generated by Django 5.0.2 on 2024-04-04 04:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0014_remove_listing_pub_date_listing_parameters_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_filter',
            name='full_place',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user_filter',
            name='furnished',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user_filter',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'male'), (1, 'female'), (2, 'either')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user_filter',
            name='length_of_stay',
            field=models.IntegerField(blank=True, choices=[(4, '4 months'), (8, '8 months'), (12, '12 months')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user_filter',
            name='max_baths',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user_filter',
            name='max_beds',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user_filter',
            name='min_baths',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user_filter',
            name='min_beds',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user_filter',
            name='move_in_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user_filter',
            name='no_price_limit',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user_filter',
            name='personal_bathroom',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user_filter',
            name='price_limit',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)]),
        ),
    ]
