# Generated by Django 5.0.2 on 2024-04-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0016_genderoption_lengthofstayoption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing_parameters',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='user_filter',
            name='full_place',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_filter',
            name='furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_filter',
            name='personal_bathroom',
            field=models.BooleanField(default=False),
        ),
    ]
