# Generated by Django 5.0.2 on 2024-04-16 03:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0018_remove_listing_parameters_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing_parameters',
            name='length_of_stay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter.lengthofstayoption'),
        ),
        migrations.AddField(
            model_name='listing_parameters',
            name='move_in_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
