# Generated by Django 5.0.2 on 2024-04-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0019_listing_parameters_length_of_stay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing_parameters',
            name='length_of_stay',
        ),
        migrations.AddField(
            model_name='listing_parameters',
            name='length_of_stay',
            field=models.ManyToManyField(blank=True, to='newsletter.lengthofstayoption'),
        ),
    ]
