# Generated by Django 5.0.2 on 2024-04-18 04:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0020_remove_listing_parameters_length_of_stay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user_filter',
            name='price_limit',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8100)]),
        ),
    ]
