# Generated by Django 5.0.2 on 2024-03-02 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter',
            old_name='own_bathroom',
            new_name='personal_bathroom',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='own_bathroom',
            new_name='personal_bathroom',
        ),
    ]
