# Generated by Django 5.0.2 on 2024-03-02 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_remove_listing_bathrooms_remove_listing_beds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='parameters',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newsletter.filter'),
        ),
    ]
