# Generated by Django 5.0.2 on 2024-03-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_neighbourhood_remove_filter_length_of_stay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='full_place',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='filter',
            name='gender',
            field=models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'either')], default=2),
        ),
    ]
